FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json turbo.json .npmrc ./
COPY apps/api/package.json ./apps/api/package.json
COPY packages/eslint-config/package.json ./packages/eslint-config/package.json
COPY packages/typescript-config/package.json ./packages/typescript-config/package.json

RUN npm ci

COPY apps/api ./apps/api
COPY packages ./packages

WORKDIR /app/apps/api
RUN npm run build:ts

EXPOSE 3001

CMD ["npm", "run", "start"]